clc
% A=12


% 2 3 4 7 9 10 11 
Ev_Nav.data(iprobabilistic,17)=0.5;
Ev_Nav.data(ideterministic,17)=1;
% 
% %INSERT INTO `gms_natural`(`T`, `Date`, `PRS`, `CO`, `D`, `BAZ`, `BAZd`, `SLW`, `SLWd`, `FP`, `RS`, `SNR`, `PROBABILITY`) VALUES 
% %([value-1],[value-2],[value-3],[value-4],[value-5],[value-6],[value-7],[value-8],[value-9],[value-10],[value-11],[value-12],[value-13])

% INSERT INTO `W_events`.`gms_natural` (`T`, `Date`, `PRS`, `CO`, `D`, `BAZ`, `BAZd`, `SLW`, `SLWd`, `FP`, `RS`, `SNR`, `PROBABILITY`) VALUES ..
% ('', '2017-03-09 02:59:47', '82', '65', '48', '218.6', '0.2', '354.9', '-0.2', '2.7', '2.4', '0', '0.5');
% 


query=['(','""',',',...
    '"',datestr(Ev_Nav.data(iprobabilistic(A),1),31),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),6)*1000)),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),4)*100)),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),3))),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),8)*10)/10),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),9)*10)/10),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),10)*10)/10),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),12)*10)/10),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),13)*10)/10),'",',...
    '"',num2str(round(Ev_Nav.data(iprobabilistic(A),15)*10)/10),'",',...
    '"','0','",',...
    '"',num2str(Ev_Nav.data(iprobabilistic(A),17)),'");'];

% query=['INSERT INTO `gm2_natural` (`T`, `Date`, `PRS`, `CO`, `D`, `BAZ`, `BAZd`, `SLW`, `SLWd`, `FP`, `RS`, `SNR`, `PROBABILITY`) VALUES ',...
%     query];
% disp(query)

query=['INSERT INTO `gms_natural` (`T`, `Date`, `PRS`, `CO`, `D`, `BAZ`, `BAZd`, `SLW`, `SLWd`, `FP`, `RS`, `SNR`, `PROBABILITY`) VALUES ',...
    query];
disp(query)