function [fitresult, gof] = iad_createFit(fint, pint)
%CREATEFIT(FINT,PINT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fint
%      Y Output: pint
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jun-2018 13:44:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fint, pint );
%xData=fint;yData=pint;
% Set up fittype and options.
ft = fittype( 'a^2/xx+b^2+2*b*a/sqrt(xx)', 'independent', 'xx', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
%opts.StartPoint = [0.0844358455109103 0.399782649098896];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure(111);
% h = plot( fitresult, xData, yData );
% % legend( h, 'pint vs. fint', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% % xlabel fint
% % ylabel pint
% grid on


