function iad_refresh_database(tablename,eventdata,torretta,date,station)
 
data=eventdata';


ii=find(data(1,:)>=date);
if isempty(ii)
    return
else
    data=data(:,ii);
    if ~isempty(torretta)
        torretta=torretta(ii);
    end
end


% iad_events2dB_delete(tablename,datestr(date,31),station) %GMT+1h
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sul Database... before 2017-2018
% T 	Date 	PRS 	CO 	D 	BAZ 	BAZd 	SLW 	SLWd 	FP 	RS 	SNR 	PROBABILITY 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Mpriv=cat(1,...
%     data(1,:)+0/24,...    %1 GMT+1h
%     round(data(6,:)*1e3),...  %2
%     round(data(4,:)*100),...
%     ceil(data(3,:)),...
%     round(data(8,:)*10)/10,...
%     round(data(9,:)*100)/100,...
%     round(data(10,:)),...
%     round(data(12,:)),...
%     round(data(13,:)*10)/10,...
%     round(data(14,:)*10)/10,...
%     ones(1,size(data,2)),...
%     data(17,:),...
%     data(17,:)); %... 13

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sul Database... after 2017
% T 	Date 	PRS 	CO 	D 	BAZ 	BAZd 	SLW 	SLWd 	FP 	RS 	SNR PROBABILITY BAZsIDX SLWsIDX BAZon BAZend Iexp
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Mpriv=cat(1,...
    data(1,:)+0/24,...    %1 GMT+1h
    round(data(6,:)*1e3),...  %2
    round(data(4,:)*100),...
    ceil(data(3,:)),...
    round(data(8,:)*10)/10,...
    round(data(9,:)*100)/100,...
    round(data(10,:)),...
    round(data(12,:)),...
    round(data(13,:)*10)/10,...
    round(data(14,:)*10)/10,...
    ones(1,size(data,2)),...
    data(17,:),...
    data(17,:),...  %... 13
    round(data(18,:)*10)/10,...
    round(data(19,:)*10)/10,...
    round(data(20,:)*10)/10,...
    round(data(21,:)*10)/10,...
    round(data(22,:)*10)/10,... %... 18
    round(data(23,:)*10)/10,...
    round(data(24,:)*10)/10); %... 20

       
iad_events2dB_insert(tablename,Mpriv',torretta,station)

return
